# 应用启动端口
server:
  port: 1011
# 数据库相关信息配置（根据实际情况修改数据库连接地址，用户名，密码）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/server_learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Root,.65
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis 相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# mybatis plus 日志输出
mybatis-plus:
  # 配置 xml 的存放路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑未删除全局值（默认 0、表示未删除）
      logic-not-delete-value: 0
      # 逻辑删除全局值（默认 1、表示已删除）
      logic-delete-value: 1