# 应用启动端口
server:
  port: 1011
# 数据库相关信息配置（根据实际情况修改数据库连接地址，用户名，密码）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_practice?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: Root,.65
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis 相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
test:
  name: zhangsan