package org.incoder.mybatis.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   部门表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_dept
 */
public class Dept {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.id
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   部门名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.dept_name
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    private String deptName;

    /**
     * Database Column Remarks:
     *   父部门 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.parent_id
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.create_time
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.update_time
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.id
     *
     * @return the value of tbl_dept.id
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.id
     *
     * @param id the value for tbl_dept.id
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.dept_name
     *
     * @return the value of tbl_dept.dept_name
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.dept_name
     *
     * @param deptName the value for tbl_dept.dept_name
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.parent_id
     *
     * @return the value of tbl_dept.parent_id
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.parent_id
     *
     * @param parentId the value for tbl_dept.parent_id
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.create_time
     *
     * @return the value of tbl_dept.create_time
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.create_time
     *
     * @param createTime the value for tbl_dept.create_time
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.update_time
     *
     * @return the value of tbl_dept.update_time
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.update_time
     *
     * @param updateTime the value for tbl_dept.update_time
     *
     * @mbg.generated Mon Mar 30 07:55:08 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}