##########################################################################
# 这个文件中通常放一些项目与环境无关的一些配置，比如服务端口等，取决于你项目的实际情况
##########################################################################
spring:
  profiles:
    active: @profileActive@
