server:
  port: 2002
# springboot 默认日志使用 logback（http://logback.qos.sh），这里使用 warn 等级日志输出
#logging:
#  level: warn

##########################################################################
# 数字，字符串，布尔配置
##########################################################################
env: prod
os: centOS
os-version: 8
# ~表示NULL值
email: incoder.xu@gmail.com
# 多行字符串可以使用 | 保留换行符，也可以使用 > 折叠换行
# + 表示保留文字块末尾的换行，- 表示删除字符串末尾的换行
message: |-
  hello world centos
# 单引号
# 会转义特殊字符，特殊字符最终只是一个普通的字符串数据
# 输出：
# A n B
name1: 'linux n centOS'
# 双引号
# 不会转义字符串里面的特殊字符，特殊字符会作为本身想表示的意思
# 输出：
# A
# B
name2: "linux n centOS"

##########################################################################
# 数组（List、Set）
##########################################################################
program-language:
  - object-c
  - swift
  - c
# 或者行内写法
program-languages: object-c,swift,c

##########################################################################
# 对象、Map（属性和值）
##########################################################################

# 对象
person:
  name: Jerry
  age: 20
# 或者行内写法
persons: {name: Jerry, age: 20}
# Map
map-object:
  maps:
    key1: value1
    key2: value2
# 或者行内写法
mapObjects.maps: {key1: value1,key2: value2}

##########################################################################
# 占位符
##########################################################################

# 随机数
secret: ${random.value}
number: ${random.int}
bignumber: ${random.long}
uuid: ${random.uuid}